"""Extract every shot in shots.json from the BMW PressClub films (source/*.mov, 1920x1080 25p) as JPEG frames
(assets/frames/<shot>/0000.jpg = the shot's in-point) and write film/shots.js for the footage layer. Run from the project root."""
import json, os, subprocess
from concurrent.futures import ThreadPoolExecutor
S = json.load(open('shots.json'))
def one(item):
    name, (film, a, b, fx, *lb) = item
    out = f'assets/frames/{name}'; os.makedirs(out, exist_ok=True)
    for f in os.listdir(out): os.remove(os.path.join(out, f))
    subprocess.run(['ffmpeg', '-v', 'error', '-y', '-ss', f'{a:.3f}', '-i', f"source/{S['films'][film]}.mov", '-t', f'{b - a:.3f}',
                    '-vf', 'fps=25', '-q:v', '2', '-start_number', '0', f'{out}/%04d.jpg'], check=True)
    return name, len(os.listdir(out)), fx, (lb[0] if lb else 0)
with ThreadPoolExecutor(6) as ex: res = list(ex.map(one, S['shots'].items()))
meta = {n: {'n': k, 'fps': 25, 'fx': fx, 'lb': lb} for n, k, fx, lb in res}
open('film/shots.js', 'w').write('// generated by scripts/prep_frames.py from shots.json\nwindow.SHOTS = ' + json.dumps(meta) + ';\n')
print(len(meta), 'shots,', sum(m['n'] for m in meta.values()), 'frames')
