"""Extract every shot in shots.json as JPEG frames (assets/frames/<shot>/0000.jpg = the shot's in-point) and write
film/shots.js for the footage layer. Run from the project root.
  mode 'full'   : a 9:16 crop around (fx, fy), zoomed by `zoom`, Lanczos-upscaled to 1080x1920 with a light unsharp.
  mode 'square' : a 1:1 crop (zoom/fx/fy) Lanczos-scaled to `size` px (default 1080). Shots that open to full frame use
                  1920, so the 9:16 frame is a 1:1 draw of the square's centre band; window-only shots use 1080.
  mode 'box'    : a crop of aspect w:h centred on (fx, fy), zoomed by `zoom`, Lanczos-scaled to w x h (window shots).
Frames are extracted at the source frame rate; the film picks the nearest frame per output frame."""
import json, os, subprocess
from concurrent.futures import ThreadPoolExecutor
S = json.load(open('shots.json'))
def probe(f):
    out = subprocess.run(['ffprobe', '-v', 'error', '-select_streams', 'v', '-show_entries', 'stream=width,height,r_frame_rate',
                          '-of', 'csv=p=0', f], capture_output=True, text=True).stdout.strip().split(',')
    w, h = int(out[0]), int(out[1]); n, d = out[2].split('/'); return w, h, float(n) / float(d)
def one(item):
    name, sh = item
    src = S['films'][sh['film']]; w, h, fps = probe(src)
    out = f'assets/frames/{name}'; os.makedirs(out, exist_ok=True)
    for f in os.listdir(out): os.remove(os.path.join(out, f))
    z = sh.get('zoom', 1.0); fx, fy = sh.get('fx', 0.5), sh.get('fy', 0.5)
    if sh.get('mode', 'full') == 'full':
        cw = min(w, h * 9 / 16) / z; ch = cw * 16 / 9
        if ch > h: ch = h / z; cw = ch * 9 / 16
        x = max(0, min(w - cw, fx * w - cw / 2)); y = max(0, min(h - ch, fy * h - ch / 2))
        vf = f'crop={cw:.1f}:{ch:.1f}:{x:.1f}:{y:.1f},scale=1080:1920:flags=lanczos,unsharp=5:5:0.45'
        W, H = 1080, 1920
    elif sh['mode'] == 'box':
        W, H = sh['w'], sh['h']; cw = w / z; ch = cw * H / W
        if ch > h: ch = h / z; cw = ch * W / H
        x = max(0, min(w - cw, fx * w - cw / 2)); y = max(0, min(h - ch, fy * h - ch / 2))
        vf = f'crop={cw:.1f}:{ch:.1f}:{x:.1f}:{y:.1f},scale={W}:{H}:flags=lanczos,unsharp=5:5:0.4'
    else:
        side = min(w, h) / z; x = max(0, min(w - side, fx * w - side / 2)); y = max(0, min(h - side, fy * h - side / 2))
        px = sh.get('size', 1080)
        vf = f'crop={side:.1f}:{side:.1f}:{x:.1f}:{y:.1f},scale={px}:{px}:flags=lanczos,unsharp=5:5:{0.5 if px > 1080 else 0.35}'
        W, H = px, px
    subprocess.run(['ffmpeg', '-v', 'error', '-y', '-ss', f"{sh['in']:.3f}", '-i', src, '-t', f"{sh['out'] - sh['in']:.3f}",
                    '-vf', vf, '-q:v', '2', '-start_number', '0', f'{out}/%04d.jpg'], check=True)
    return name, {'n': len(os.listdir(out)), 'fps': round(fps, 4), 'w': W, 'h': H, 'mode': sh.get('mode', 'full')}
with ThreadPoolExecutor(6) as ex: res = dict(ex.map(one, S['shots'].items()))
open('film/shots.js', 'w').write('// generated by scripts/prep_frames.py from shots.json\nwindow.SHOTS = ' + json.dumps(res) + ';\n')
print(len(res), 'shots,', sum(m['n'] for m in res.values()), 'frames')
