// generated by scripts/prep_frames.py from shots.json
window.SHOTS = {"beach": {"n": 39, "fps": 23.976, "w": 760, "h": 1000, "mode": "box"}, "orchid": {"n": 20, "fps": 23.976, "w": 760, "h": 1000, "mode": "box"}, "jersey": {"n": 12, "fps": 23.976, "w": 760, "h": 1000, "mode": "box"}, "dance": {"n": 62, "fps": 23.976, "w": 760, "h": 1000, "mode": "box"}};
