# Place the Kokoro lines on the beat grid (timeline.json "vo": {id: beat}) → audio/vo.wav (48 kHz mono),
# audio/vo_placed.json (for film/data.js: id, who, sub, t0, t1, b0, b1, words) and film/vo_env.js (mouth envelopes per
# speaker, one value per output frame, 0..1, so the avatars' mouths are a pure function of t).
import json, numpy as np, soundfile as sf
TL = json.load(open('timeline.json')); S = json.load(open('vo_script.json')); D = json.load(open('audio/vo/lines.json'))
B = json.load(open('beats.json'))['beat']; SR = 48000; FPS = TL['fps']; N = int(TL['duration'] * SR)
vo = np.zeros(N, np.float32); spk = {'B': np.zeros(N, np.float32), 'C': np.zeros(N, np.float32)}
placed = []
for L in S['lines']:
    b0 = TL['vo'][L['id']]; t0 = b0 * B
    a, sr = sf.read(f"audio/vo/{L['id']}.wav", dtype='float32'); assert sr == SR
    i0 = int(round(t0 * SR)); i1 = min(N, i0 + len(a))
    vo[i0:i1] += a[:i1 - i0]; spk[L['who']][i0:i1] += a[:i1 - i0]
    t1 = t0 + len(a) / SR
    placed.append({'id': L['id'], 'who': L['who'], 'sub': L['sub'], 't0': round(t0, 4), 't1': round(t1, 4), 'b0': b0, 'b1': round(t1 / B, 3),
                   'words': [{'w': w['w'], 'b': round((t0 + w['s']) / B, 3)} for w in D[L['id']].get('words', [])]})
    print(f"{L['id']:4s} {L['who']} b{b0:<5} {t0:6.2f}–{t1:6.2f}s  {L['sub']}")
for a, b in zip(placed, placed[1:]):
    assert b['t0'] >= a['t1'] - 1e-3, f"{a['id']} overlaps {b['id']}"
sf.write('audio/vo.wav', vo, SR, subtype='PCM_24')
json.dump(placed, open('audio/vo_placed.json', 'w'), ensure_ascii=False, indent=1)
env = {}; hop = SR // FPS
for k, x in spk.items():
    n = len(x) // hop; r = np.sqrt(np.mean(x[:n * hop].reshape(n, hop) ** 2, axis=1))
    r = np.clip((r - 0.01) / (np.percentile(r[r > 0.01], 95) - 0.01 + 1e-9), 0, 1)
    r = np.convolve(r, [0.25, 0.5, 0.25], 'same')
    env[k] = [round(float(v), 3) for v in r]
open('film/vo_env.js', 'w').write(f"// GENERATED by scripts/vo_place.py — mouth envelopes, one value per frame at {FPS} fps\nwindow.VOENV = {json.dumps({'fps': FPS, **env})};\n")
print('audio/vo.wav', round(N / SR, 2), 's · film/vo_env.js written')
